### ISSUE TITLE
allow auto-detecting of repo type when possible

### ISSUE THREAD

**Issue by dunn** [samertm/homebrew-go-resources#1]
Homebrew can sometimes detect the VCS to use for a url: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/download_strategy.rb#L829-L850

This saves us from having to specify `:using => :whatever`, and it'd be great if homebrew-go-resources could look out for at least the most common ones and format the `go_resource` accordingly.

The most common case is for GitHub urls; the only change would be to append `.git`.

**Comment by samertm** [comment]
Fixed, thanks for bringing this to my attention!
